@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor "Application Developer" as actorUser

rectangle "BlockBuilder Framework API" {
' UC1
  usecase "UC1 Initiates a Framework instance" as UC1

' UC2
  usecase "UC2 Invokes a Ledger DataSource" as UC2
  usecase "UC2.1 Explores Ledger Records" as UC2.1
  usecase "UC2.2 Submits a Ledger Transaction" as UC2.2
  usecase "UC2.3 Fetches a Ledger Transaction" as UC2.3

'UC3
  usecase "UC3 Invokes a Liquidity Provider DataSource" as UC3
  usecase "UC3.1 Explores Exchange Prices" as UC3.1
  usecase "UC3.2 Submits a Exchange Transaction" as UC3.2
  usecase "UC3.3 Fetches a Exchange Transaction" as UC3.3

' UC2 extensions
  UC2 <|-- UC2.1
  UC2 <|-- UC2.2
  UC2 <|-- UC2.3

' UC3 extensions
  UC3 <|-- UC3.1
  UC3 <|-- UC3.2
  UC3 <|-- UC3.3

}
actorUser --> UC1
actorUser --> UC2
actorUser --> UC3

@enduml
